name: deploy

inputs:
  environment: 
    required: true
    
defaults:
  run:
    shell: bash
    
runs:
  using: "composite"
  steps:

  - name: Display file content
    run: |
      cat test.txt
   
  - name: Display environment
    run: |
      echo ${{ env.env_name }}
