name: deploy

inputs:
  environment: 
    required: true
    
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3

  - name: Display file content
    run: |
      cat test.txt
      echo ${{ env.env_name }}
