name: CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: deploy
        uses: ./.github/template
        with:
          environment: dev

  build_prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: deploy
        uses: ./.github/template
        with:
          environment: prod
