name: CI

on:
  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: ./.github/template
        with:
          environment: dev

  build_prod:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: ./.github/template
        with:
          environment: prod
          secret: ${{ secret.VERY_SECRET_VARIABLE }}
