name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: ./.github/template/test
        with:
          environment: dev
          secret: ${{ secrets.VERY_SECRET_VARIABLE }}

  build_prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: build_dev
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: deploy
        uses: ./.github/template/test
        with:
          environment: prod
          secret: ${{ secrets.VERY_SECRET_VARIABLE }}
